# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0002_bom_bomdetail_djangomigrations_item_loadsettledetailsinfocopy_tbasareainfo_tbasskuprice_tbuyerinfo_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gpc', models.CharField(blank=True, max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('products', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxrate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(blank=True, db_column='time', null=True)),
                ('deal_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'tax_rate',
                'managed': False,
            },
        ),
    ]
